### ISSUE TITLE
Consider making the `daemonScript` optional

### ISSUE THREAD

**Issue by pastelsky** [isaacs/sock-daemon#7]
Sometimes, you might already have a long-living process running (e.g. file watcher), and you're just looking for a reliable communications layer between the long-running process and other ephemeral processes without the communications layer essentially taking over the starting/stopping of the server.

It seems that `sock-daemon` was created for a particular purpose, but it'd be helpful to re-use this behavior for the case I described above. 

Would you consider making the `daemonScript` option optional in such cases?

**Comment by isaacs** [comment]
I don't understand. If it doesn't have a `daemonScript`, then how does it know how to start the daemon on demand?

If you're suggesting that the client should _not_ start the daemon when needed, then it's pretty hazardous, because it could try connecting to a unix socket that doesn't exist, or worse yet, _does_ exist, but with nothing listening for connections, so it'd just time out.

Almost all of the logic in this module exists for the sole purpose of managing that long-running process, not starting if it's already running, starting it on demand if it isn't, killing it if it stops responding, etc.

Maybe what you're really asking for is not to make the `daemonScript` optional, but to abstract out the request/response logic as a standalone library? I could see that being useful. But it'd be a different project, not a feature of this one.
